// src/app/api/create-playlist/route.ts

import { NextRequest, NextResponse } from "next/server";
import { getToken } from "next-auth/jwt";
import OpenAI from "openai";

const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET!;

export async function POST(req: NextRequest) {
  try {
    // 1) Get access token from session
    const token = await getToken({ req, secret: NEXTAUTH_SECRET });
    if (!token?.accessToken) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const accessToken = token.accessToken;

    // 2) Get prompt
    const { prompt } = await req.json();
    if (!prompt) {
      return NextResponse.json({ error: "Missing prompt" }, { status: 400 });
    }

    // 3) Get suggestions from OpenAI
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY! });
    const aiResp = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        { role: "system", content: "You are a music expert..." },
        {
          role: "user",
          content: `Generate a list of 10 songs or artists that fit the vibe: "${prompt}". Respond as a numbered list.`,
        },
      ],
    });

    const suggestionText = aiResp.choices[0]?.message?.content || "";
    const queries = suggestionText
      .split("\n")
      .map((line) => line.replace(/^\d+\.\s*/, "").trim())
      .filter(Boolean);

    // 4) Search Spotify for each suggestion
    const headers = {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    };

    const uris: string[] = [];
    for (const query of queries) {
      const searchRes = await fetch(
        `https://api.spotify.com/v1/search?q=${encodeURIComponent(query)}&type=track&limit=5`,
        { headers }
      );

      if (searchRes.status === 401) {
        return NextResponse.json({ error: "Spotify token expired. Please re-login." }, { status: 401 });
      }

      const searchData = await searchRes.json();
      const track = searchData.tracks?.items?.find(
        (t: any) =>
          !/karaoke|tribute|cover|made famous|originally performed/i.test(t.name) &&
          !/karaoke|tribute|cover/i.test(t.artists[0]?.name)
      );
      if (track) uris.push(track.uri);
    }

    if (uris.length === 0) {
      return NextResponse.json(
        { error: "No valid songs found for this prompt." },
        { status: 404 }
      );
    }

    // 5) Get user info
    const meRes = await fetch("https://api.spotify.com/v1/me", { headers });
    const meData = await meRes.json();
    const userId = meData.id;

    // 6) Create playlist
    const playlistRes = await fetch(
      `https://api.spotify.com/v1/users/${userId}/playlists`,
      {
        method: "POST",
        headers,
        body: JSON.stringify({
          name: `Prompt: ${prompt}`,
          description: "Generated by AI DJ",
          public: false,
        }),
      }
    );
    const playlist = await playlistRes.json();

    // 7) Add songs
    await fetch(
      `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
      {
        method: "POST",
        headers,
        body: JSON.stringify({ uris }),
      }
    );

    // 8) Return link
    return NextResponse.json({ url: playlist.external_urls.spotify });
  } catch (err: any) {
    console.error("create-playlist error:", err);
    return NextResponse.json(
      { error: "Internal Server Error", details: err.message || "" },
      { status: 500 }
    );
  }
}
